-- ============================================================================
-- BeautyBoxMedia /bizmanage — Supabase schema (mirrors the live database)
-- Run in your Supabase project: SQL Editor -> paste -> Run.
-- Creates the `brands` and `dropdown_options` tables, enables Row-Level
-- Security (authenticated users only), and seeds the dropdown values.
--
-- NOTE: brand rows themselves are managed from the app, so they are NOT
-- re-seeded here.
-- ============================================================================

-- 1. brands ------------------------------------------------------------------
create table if not exists public.brands (
  id             bigint generated by default as identity primary key,
  brand          text not null default '',
  account_name   text not null default '',
  brand_registry text not null default '',
  reseller_type  text not null default '',
  num_asins      text not null default '',
  owned_by       text not null default '',
  urgency        text not null default '',
  -- Sparse 1–30 ranking. Nullable = unranked. Unique so no two brands share a rank.
  priority       integer unique check (priority is null or (priority >= 1 and priority <= 30)),
  status         text not null default 'Active',
  est_sow        text not null default '',
  note           text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

comment on table public.brands is
  'iCommerceteam multi-brand Amazon portfolio (NRG/RMR + The Beauty Box).';

-- 2. dropdown_options --------------------------------------------------------
-- Allowed values for each BizManage select field. Add a value by inserting a
-- row — no code/migration change needed.
create table if not exists public.dropdown_options (
  id         bigint generated always as identity primary key,
  field      text not null,
  value      text not null,
  label      text,
  sort_order integer not null default 0,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.dropdown_options is
  'Allowed values for every BizManage dropdown (account_name, brand_registry, reseller_type, owned_by, urgency, status, est_sow).';

-- Prevents duplicate options (e.g. two sessions using "+ Add new…" at once).
create unique index if not exists dropdown_options_field_value_uniq
  on public.dropdown_options (field, lower(value));

-- 3. Row-Level Security ------------------------------------------------------
-- Only signed-in (authenticated) users may read or write. This is what makes it
-- safe to ship the public anon key in the static site.
alter table public.brands enable row level security;
alter table public.dropdown_options enable row level security;

drop policy if exists "brands_select_authenticated" on public.brands;
create policy "brands_select_authenticated"
  on public.brands for select to authenticated using (true);

drop policy if exists "brands_write_authenticated" on public.brands;
create policy "brands_write_authenticated"
  on public.brands for all to authenticated using (true) with check (true);

drop policy if exists "dropdown_options_select_authenticated" on public.dropdown_options;
create policy "dropdown_options_select_authenticated"
  on public.dropdown_options for select to authenticated using (true);

drop policy if exists "dropdown_options_write_authenticated" on public.dropdown_options;
create policy "dropdown_options_write_authenticated"
  on public.dropdown_options for all to authenticated using (true) with check (true);

-- 4. Seed dropdown values ----------------------------------------------------
-- Only seeds when the table is empty, so re-running this file is safe.
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('account_name',   'NRG', 1),
  ('account_name',   'RMR', 2),
  ('account_name',   'TBB', 3),
  ('account_name',   'TB',  4),
  ('brand_registry', 'Yes', 1),
  ('brand_registry', 'No',  2),
  ('brand_registry', 'N/A', 3),
  ('reseller_type',  'Exclusive',                       1),
  ('reseller_type',  'Semi-Exclusive',                  2),
  ('reseller_type',  'Pending Exclusive',               3),
  ('reseller_type',  'Reseller',                        4),
  ('reseller_type',  'Exclusive under Skin Revolution', 5),
  ('reseller_type',  'Not specified',                   6),
  ('owned_by',       'BBMEDIA', 1),
  ('owned_by',       'Regina',  2),
  ('owned_by',       'Mariann', 3),
  ('urgency',        'High',   1),
  ('urgency',        'Medium', 2),
  ('urgency',        'Low',    3),
  ('status',         'Active',      1),
  ('status',         'Closing Out', 2)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options);

-- 4b. est_sow seed — idempotent independently of the block above, because that
-- block only runs when the table is empty and live databases already have rows.
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('est_sow', 'High',   1),
  ('est_sow', 'Medium', 2),
  ('est_sow', 'Low',    3)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'est_sow');
