-- ============================================================================
-- BeautyBoxMedia /bizmanage — Supabase schema (mirrors the live database)
-- Run in your Supabase project: SQL Editor -> paste -> Run.
-- Creates the `brands` and `dropdown_options` tables, enables Row-Level
-- Security (authenticated users only), and seeds the dropdown values.
--
-- NOTE: brand rows themselves are managed from the app, so they are NOT
-- re-seeded here.
-- ============================================================================

-- 1. brands ------------------------------------------------------------------
create table if not exists public.brands (
  id             bigint generated by default as identity primary key,
  brand          text not null default '',
  account_name   text not null default '',
  brand_registry text not null default '',
  reseller_type  text not null default '',
  num_asins      text not null default '',
  owned_by       text not null default '',
  assignee       text not null default '',
  urgency        text not null default '',
  -- High / Medium / Low level, same vocabulary as urgency (see dropdown_options).
  priority       text not null default '',
  status         text not null default 'Active',
  est_sow        text not null default '',
  note           text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

comment on table public.brands is
  'iCommerceteam multi-brand Amazon portfolio (NRG/RMR + The Beauty Box).';

-- Migration for live databases created before the column existed; the
-- create-table above only applies to fresh installs.
alter table public.brands add column if not exists assignee text not null default '';

-- Priority is a shared 1-30 ranking picked in the app: each number belongs to
-- at most one brand. Legacy High/Medium/Low values are exempt until re-ranked.
create unique index if not exists brands_priority_number_uniq
  on public.brands (priority)
  where priority ~ '^[0-9]+$';

-- 2. dropdown_options --------------------------------------------------------
-- Allowed values for each BizManage select field. Add a value by inserting a
-- row — no code/migration change needed.
create table if not exists public.dropdown_options (
  id         bigint generated always as identity primary key,
  field      text not null,
  value      text not null,
  label      text,
  sort_order integer not null default 0,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.dropdown_options is
  'Allowed values for every BizManage dropdown (account_name, brand_registry, reseller_type, owned_by, assignee, urgency, status, est_sow). Priority is a computed 1-30 ranking, not served from here.';

-- Prevents duplicate options (e.g. two sessions using "+ Add new…" at once).
create unique index if not exists dropdown_options_field_value_uniq
  on public.dropdown_options (field, lower(value));

-- 3. Row-Level Security ------------------------------------------------------
-- Only signed-in (authenticated) users may read or write. This is what makes it
-- safe to ship the public anon key in the static site.
alter table public.brands enable row level security;
alter table public.dropdown_options enable row level security;

drop policy if exists "brands_select_authenticated" on public.brands;
create policy "brands_select_authenticated"
  on public.brands for select to authenticated using (true);

drop policy if exists "brands_write_authenticated" on public.brands;
create policy "brands_write_authenticated"
  on public.brands for all to authenticated using (true) with check (true);

drop policy if exists "dropdown_options_select_authenticated" on public.dropdown_options;
create policy "dropdown_options_select_authenticated"
  on public.dropdown_options for select to authenticated using (true);

drop policy if exists "dropdown_options_write_authenticated" on public.dropdown_options;
create policy "dropdown_options_write_authenticated"
  on public.dropdown_options for all to authenticated using (true) with check (true);

-- 4. Seed dropdown values ----------------------------------------------------
-- Only seeds when the table is empty, so re-running this file is safe.
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('account_name',   'NRG', 1),
  ('account_name',   'RMR', 2),
  ('account_name',   'TBB', 3),
  ('account_name',   'TB',  4),
  ('brand_registry', 'Yes', 1),
  ('brand_registry', 'No',  2),
  ('brand_registry', 'N/A', 3),
  ('reseller_type',  'Exclusive',                       1),
  ('reseller_type',  'Semi-Exclusive',                  2),
  ('reseller_type',  'Pending Exclusive',               3),
  ('reseller_type',  'Reseller',                        4),
  ('reseller_type',  'Exclusive under Skin Revolution', 5),
  ('reseller_type',  'Not specified',                   6),
  ('owned_by',       'BBMEDIA', 1),
  ('owned_by',       'Regina',  2),
  ('owned_by',       'Mariann', 3),
  ('assignee',       'iCommteam', 1),
  ('assignee',       'Umar',      2),
  ('assignee',       'Ahmad',     3),
  ('assignee',       'Basit',     4),
  ('assignee',       'Azmat',     5),
  ('assignee',       'Kiran',     6),
  ('urgency',        'High',   1),
  ('urgency',        'Medium', 2),
  ('urgency',        'Low',    3),
  ('status',         'Active',      1),
  ('status',         'Closing Out', 2)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options);

-- 4b. est_sow seed — idempotent independently of the block above, because that
-- block only runs when the table is empty and live databases already have rows.
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('est_sow', 'High',   1),
  ('est_sow', 'Medium', 2),
  ('est_sow', 'Low',    3)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'est_sow');

-- 4c. priority options are computed in the app (1-30 ranking) since the
-- 2026-07 rework; retire any seeded rows left over from older installs.
update public.dropdown_options set active = false where field = 'priority' and active;

-- 4d. assignee seed — idempotent for the same reason as 4b.
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('assignee', 'iCommteam', 1),
  ('assignee', 'Umar',      2),
  ('assignee', 'Ahmad',     3),
  ('assignee', 'Basit',     4),
  ('assignee', 'Azmat',     5),
  ('assignee', 'Kiran',     6)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'assignee');

-- 5. tasks ---------------------------------------------------------------
create table if not exists public.tasks (
  id         bigint generated by default as identity primary key,
  title      text not null default '',
  status     text not null default 'To do',
  assignee   text not null default '',
  due_date   date,
  brand      text not null default '',
  note       text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.tasks enable row level security;
drop policy if exists "tasks_select_authenticated" on public.tasks;
create policy "tasks_select_authenticated"
  on public.tasks for select to authenticated using (true);
drop policy if exists "tasks_write_authenticated" on public.tasks;
create policy "tasks_write_authenticated"
  on public.tasks for all to authenticated using (true) with check (true);

-- 6. leads ---------------------------------------------------------------
create table if not exists public.leads (
  id           bigint generated by default as identity primary key,
  company      text not null default '',
  contact_name text not null default '',
  email        text not null default '',
  stage        text not null default 'New',
  assignee     text not null default '',
  est_value    numeric(12,2),
  note         text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
alter table public.leads enable row level security;
drop policy if exists "leads_select_authenticated" on public.leads;
create policy "leads_select_authenticated"
  on public.leads for select to authenticated using (true);
drop policy if exists "leads_write_authenticated" on public.leads;
create policy "leads_write_authenticated"
  on public.leads for all to authenticated using (true) with check (true);

-- 7. finance_entries -------------------------------------------------------
-- One ledger for both money directions; Cashflow and P&L aggregate it.
create table if not exists public.finance_entries (
  id          bigint generated by default as identity primary key,
  kind        text not null check (kind in ('income', 'expense')),
  entry_date  date not null default current_date,
  description text not null default '',
  category    text not null default '',
  amount      numeric(12,2) not null default 0,
  account     text not null default '',
  note        text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists finance_entries_kind_date_idx
  on public.finance_entries (kind, entry_date);
alter table public.finance_entries enable row level security;
drop policy if exists "finance_select_authenticated" on public.finance_entries;
create policy "finance_select_authenticated"
  on public.finance_entries for select to authenticated using (true);
drop policy if exists "finance_write_authenticated" on public.finance_entries;
create policy "finance_write_authenticated"
  on public.finance_entries for all to authenticated using (true) with check (true);

-- 8. Dropdown seeds for the new screens — idempotent per field (style of 4b).
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('task_status', 'To do',       1),
  ('task_status', 'In progress', 2),
  ('task_status', 'Done',        3)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'task_status');

insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('lead_stage', 'New',       1),
  ('lead_stage', 'Contacted', 2),
  ('lead_stage', 'Meeting',   3),
  ('lead_stage', 'Proposal',  4),
  ('lead_stage', 'Won',       5),
  ('lead_stage', 'Lost',      6)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'lead_stage');

insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('income_category', 'Retainer',      1),
  ('income_category', 'Commission',    2),
  ('income_category', 'Project',       3),
  ('income_category', 'Product Sales', 4),
  ('income_category', 'Other',         5)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'income_category');

insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('expense_category', 'Payroll',     1),
  ('expense_category', 'Software',    2),
  ('expense_category', 'Advertising', 3),
  ('expense_category', 'Contractors', 4),
  ('expense_category', 'Fees',        5),
  ('expense_category', 'Other',       6)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'expense_category');

-- 9. agency_clients ----------------------------------------------------------
-- The agency's client roster, shown on the Agency Clients screen.
-- Service/status vocabularies live in dropdown_options (fields
-- `client_service`, `client_status`); assignees share the brands `assignee`.
create table if not exists public.agency_clients (
  id           bigint generated by default as identity primary key,
  client       text not null default '',
  contact_name text not null default '',
  email        text not null default '',
  phone        text not null default '',
  service      text not null default '',
  status       text not null default 'Active',
  assignee     text not null default '',
  start_date   date,
  retainer     numeric(12,2),
  note         text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
alter table public.agency_clients enable row level security;
drop policy if exists "agency_clients_select_authenticated" on public.agency_clients;
create policy "agency_clients_select_authenticated"
  on public.agency_clients for select to authenticated using (true);
drop policy if exists "agency_clients_write_authenticated" on public.agency_clients;
create policy "agency_clients_write_authenticated"
  on public.agency_clients for all to authenticated using (true) with check (true);

-- Dropdown seeds — idempotent per field (style of 4b).
insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('client_status', 'Active',     1),
  ('client_status', 'Onboarding', 2),
  ('client_status', 'Paused',     3),
  ('client_status', 'Ended',      4)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'client_status');

insert into public.dropdown_options (field, value, sort_order)
select * from (values
  ('client_service', 'Marketplaces',    1),
  ('client_service', 'DTC',             2),
  ('client_service', 'Growth & Data',   3),
  ('client_service', 'Full Management', 4),
  ('client_service', 'Consulting',      5)
) as seed(field, value, sort_order)
where not exists (select 1 from public.dropdown_options where field = 'client_service');

-- 10. avatars storage bucket -------------------------------------------------
-- Public read; each signed-in user manages only objects inside their own
-- `<user-id>/...` folder (profile photos).
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- No SELECT policy on purpose: a public bucket serves object URLs without
-- one, and adding it would let clients LIST every file in the bucket.
drop policy if exists "avatars_public_read" on storage.objects;

drop policy if exists "avatars_owner_insert" on storage.objects;
create policy "avatars_owner_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars_owner_update" on storage.objects;
create policy "avatars_owner_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars_owner_delete" on storage.objects;
create policy "avatars_owner_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
