-- Seed: iCommerceteam Brand Portfolio
-- Generated from the "CURRENT BRANDS - AS OF JUNE 2026" export (58 brands).
-- Idempotent: re-running refreshes every row from this file (upsert on id).
-- user_account is the seller account; source pairs were split NRG/RMR->NRG,
-- TBB/TB->TBB (re-assign the RMR / TB ones per brand as needed).
-- Column order:
--   id, brand, user_account, brand_registry, reseller_type, num_asins,
--   account_name, owned_by, urgency, priority, status, est_sow, note

insert into public.brands
  (id, brand, user_account, brand_registry, reseller_type, num_asins,
   account_name, owned_by, urgency, priority, status, est_sow, note)
values
  (1, 'Ariston', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (2, 'Baobab', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', 'Affiliation not specified in source'),
  (3, 'Bodi Fresh', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (4, 'Brandywine', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', ''),
  (5, 'Demeter', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (6, 'H-42', 'NRG', 'Yes', 'Exclusive for ASINs we create under Skin Revolution', null, '', '', '', null, 'Active', '', ''),
  (7, 'Inglot', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', 'Also on TBB/TB list (Semi-Exclusive)'),
  (8, 'Kitoko', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', ''),
  (9, 'Leather Luster', 'NRG', 'Yes', 'Exclusive for ASINs we create under Skin Revolution', null, '', '', '', null, 'Active', '', ''),
  (10, 'Midway', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', ''),
  (11, 'Milagros', 'NRG', 'Yes', 'Exclusive for ASINs we create under Skin Revolution', null, '', '', '', null, 'Active', '', ''),
  (12, 'Mina Brow', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (13, 'Olé Capilar', 'NRG', 'Yes', 'Exclusive for ASINs we create under Skin Revolution', null, '', '', '', null, 'Active', '', ''),
  (14, 'Ritual Botanico', 'NRG', 'Yes', 'Exclusive for ASINs we create under Skin Revolution', null, '', '', '', null, 'Active', '', ''),
  (15, 'Scimera', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', 'Also on TBB/TB list (Exclusive)'),
  (16, 'Sqwinchers', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', ''),
  (17, 'Two Old Goats', 'NRG', 'No', 'Reseller', null, '', '', '', null, 'Active', '', ''),
  (18, 'WPP', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', 'Color mask variation only, for now'),
  (19, 'Y-Not Natural', 'NRG', 'Yes', 'Exclusive', null, '', '', '', null, 'Active', '', 'Need to determine if there is a path forward'),
  (20, 'Do/Mastey', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', ''),
  (21, 'Glimmer Goddess', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', 'Closing out on NRG; still active on TBB/TB'),
  (22, 'Kiara Sky', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', 'Also closing out on TBB/TB'),
  (23, 'Life Factory', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', ''),
  (24, 'Lineco', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', ''),
  (25, 'Plantlife', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', ''),
  (26, 'Saratoga Olive Oil Co', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', ''),
  (27, 'Staleks', 'NRG', 'No', 'Not specified', null, '', '', '', null, 'Closing Out', '', 'Also closing out on TBB/TB'),
  (28, 'NutriRoot', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (29, 'Cosmedica Skincare', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (30, 'Chihtsai', 'TBB', 'N/A', 'Pending Exclusive', null, '', '', '', null, 'Active', '', ''),
  (31, 'Eagle Fortress', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (32, 'El Gallito Coffee', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (33, 'French Farm', 'TBB', 'N/A', 'Created new ASINs under TBB Brand Registry', null, '', '', '', null, 'Active', '', ''),
  (34, 'Glimmer Goddess', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (35, 'Golden Rabbit', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', ''),
  (36, 'Govino', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (37, 'H2Pro', 'TBB', 'N/A', 'Not specified', null, '', '', '', null, 'Active', '', ''),
  (38, 'Inglot', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', 'Also on NRG list (Reseller)'),
  (39, 'Kai', 'TBB', 'N/A', 'Not specified', null, '', '', '', null, 'Active', '', ''),
  (40, 'Le Blanc', 'TBB', 'N/A', 'Not specified', null, '', '', '', null, 'Active', '', ''),
  (41, 'Lifefactory', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (42, 'Lisap Haircare', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (43, 'Mason Pearson', 'TBB', 'N/A', 'Not specified', null, '', '', '', null, 'Active', '', ''),
  (44, 'Mizon', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', 'Korean skincare · Shopify full SKU / Amazon all besides snail mucin'),
  (45, 'Nailplex Shield', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', ''),
  (46, 'Nailtiques', 'TBB', 'N/A', 'Not specified', null, '', '', '', null, 'Active', '', ''),
  (47, 'Orange Chronic', 'TBB', 'N/A', 'Created new ASINs under TBB Brand Registry', null, '', '', '', null, 'Active', '', ''),
  (48, 'Redavid', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (49, 'Restorsea', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', ''),
  (50, 'Roxanne Rizzo', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', ''),
  (51, 'Ruminae', 'TBB', 'N/A', 'Pending Exclusive', null, '', '', '', null, 'Active', '', ''),
  (52, 'Scimera', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', 'Also on NRG list (Exclusive)'),
  (53, 'Sonoma Syrup Co', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', ''),
  (54, 'The Balm Cosmetics', 'TBB', 'N/A', 'Semi-Exclusive', null, '', '', '', null, 'Active', '', ''),
  (55, 'Three Lollies', 'TBB', 'N/A', 'Not specified', null, '', '', '', null, 'Active', '', ''),
  (56, 'Toweldry', 'TBB', 'N/A', 'Pending Exclusive', null, '', '', '', null, 'Active', '', ''),
  (57, 'Vivioptal', 'TBB', 'N/A', 'Pending Exclusive', null, '', '', '', null, 'Active', '', ''),
  (58, 'Watercolors Haircare', 'TBB', 'N/A', 'Exclusive', null, '', '', '', null, 'Active', '', '')
on conflict (id) do update set
  brand          = excluded.brand,
  user_account   = excluded.user_account,
  brand_registry = excluded.brand_registry,
  reseller_type  = excluded.reseller_type,
  num_asins      = excluded.num_asins,
  account_name   = excluded.account_name,
  owned_by       = excluded.owned_by,
  urgency        = excluded.urgency,
  priority       = excluded.priority,
  status         = excluded.status,
  est_sow        = excluded.est_sow,
  note           = excluded.note;
