-- ============================================================================
-- BeautyBoxMedia — Unit Economics schema (BBMEDIA Supabase project)
-- Replaces the "Profit-Calc" Google Sheet with two tables + a computed view.
--
--   cogs            product identity + purchase cost, managed by the team
--   unit_economics  Amazon-synced fees/price + per-row planning inputs
--   unit_economics_view  the Profit-Calc formulas, one row per account+SKU
--
-- Accounts use the same short codes as /bizconsole: NRG, RMR, TBB, TB, BCP.
-- Amazon data is refreshed from BigQuery (amzbi-418608.amazon_source_data);
-- see UNIT_ECONOMICS.md for the source queries. Re-running this file is safe.
-- ============================================================================

-- 1. cogs --------------------------------------------------------------------
create table if not exists public.cogs (
  id                  bigint generated by default as identity primary key,
  account             text not null,
  sku                 text not null,
  asin                text not null default '',
  title               text not null default '',
  item_name           text not null default '',
  brand               text not null default '',
  purchase_cost       numeric(12,2) not null default 0,
  product_group       text not null default '',
  fulfillment_channel text not null default '',   -- FBA / FBM
  note                text not null default '',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.cogs is
  'Product master + purchase cost (COGS) per account+SKU. Accounts: NRG, RMR, TBB, TB, BCP. Identity fields enriched from BigQuery; purchase_cost managed by the team.';

create unique index if not exists cogs_account_sku_uniq
  on public.cogs (account, sku);
create index if not exists cogs_account_brand_idx
  on public.cogs (account, brand);

-- 2. unit_economics ----------------------------------------------------------
create table if not exists public.unit_economics (
  id                 bigint generated by default as identity primary key,
  account            text not null,
  sku                text not null,
  -- Synced from Amazon (BigQuery) --------------------------------------------
  size_tier          text not null default '',
  storage_fee        numeric(12,4) not null default 0,  -- per unit
  fulfillment_fee    numeric(12,2) not null default 0,  -- FBA pick&pack per unit
  current_price      numeric(12,2) not null default 0,
  referral_fee       numeric(12,2) not null default 0,  -- per unit (15% of price when Amazon has no estimate)
  synced_at          timestamptz,
  -- Manual inputs (mirror the Profit-Calc sheet) -----------------------------
  prep_cost          numeric(12,2) not null default 0,
  inbound_cost       numeric(12,2) not null default 0,
  discount_pct       numeric(6,4),  -- e.g. 0.20 = 20% off; null = no discount planned
  desired_profit_pct numeric(6,4),  -- e.g. 0.25 = target 25% margin; drives suggested_price
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

comment on table public.unit_economics is
  'Per-SKU unit economics (Profit-Calc equivalent). Fees/price synced from BigQuery Amazon reports; prep/inbound/discount/desired-profit are manual planning inputs. Joined with cogs in unit_economics_view.';

create unique index if not exists unit_economics_account_sku_uniq
  on public.unit_economics (account, sku);

-- 3. Row-Level Security ------------------------------------------------------
alter table public.cogs enable row level security;
alter table public.unit_economics enable row level security;

drop policy if exists "cogs_select_authenticated" on public.cogs;
create policy "cogs_select_authenticated"
  on public.cogs for select to authenticated using (true);

drop policy if exists "cogs_write_authenticated" on public.cogs;
create policy "cogs_write_authenticated"
  on public.cogs for all to authenticated using (true) with check (true);

drop policy if exists "unit_economics_select_authenticated" on public.unit_economics;
create policy "unit_economics_select_authenticated"
  on public.unit_economics for select to authenticated using (true);

drop policy if exists "unit_economics_write_authenticated" on public.unit_economics;
create policy "unit_economics_write_authenticated"
  on public.unit_economics for all to authenticated using (true) with check (true);

-- 4. unit_economics_view -----------------------------------------------------
-- One row per account+SKU with every Profit-Calc formula computed.
-- security_invoker makes the view respect the tables' RLS (authenticated only).
create or replace view public.unit_economics_view
with (security_invoker = true) as
select
  ue.id,
  ue.account,
  c.brand,
  c.asin,
  ue.sku,
  c.title,
  c.item_name,
  c.product_group,
  c.fulfillment_channel,
  -- Costs
  c.purchase_cost,
  ue.prep_cost,
  ue.inbound_cost,
  c.purchase_cost + ue.prep_cost + ue.inbound_cost                as total_cost,
  -- Amazon fees & price
  ue.size_tier,
  ue.storage_fee,
  ue.fulfillment_fee,
  ue.current_price,
  ue.referral_fee,
  ue.storage_fee + ue.fulfillment_fee + ue.referral_fee           as total_fee,
  -- Profitability
  ue.current_price
    - (c.purchase_cost + ue.prep_cost + ue.inbound_cost)
    - (ue.storage_fee + ue.fulfillment_fee + ue.referral_fee)     as profit,
  case when ue.current_price > 0 then
    round((ue.current_price
      - (c.purchase_cost + ue.prep_cost + ue.inbound_cost)
      - (ue.storage_fee + ue.fulfillment_fee + ue.referral_fee))
      / ue.current_price, 4)
  end                                                             as margin_pct,
  case when ue.current_price > 0 then
    round((ue.current_price
      - (c.purchase_cost + ue.prep_cost + ue.inbound_cost)
      - (ue.storage_fee + ue.fulfillment_fee + ue.referral_fee))
      / ue.current_price, 4)
  end                                                             as be_tacos,
  -- Discount planning (referral fee scales with the discounted price)
  ue.discount_pct,
  case when ue.discount_pct is not null then
    round(ue.current_price * (1 - ue.discount_pct), 2)
  end                                                             as discounted_price,
  case when ue.discount_pct is not null and ue.current_price > 0 then
    round(ue.current_price * (1 - ue.discount_pct)
      - (c.purchase_cost + ue.prep_cost + ue.inbound_cost)
      - ue.storage_fee - ue.fulfillment_fee
      - (ue.referral_fee / ue.current_price)
        * ue.current_price * (1 - ue.discount_pct), 2)
  end                                                             as discounted_profit,
  case when ue.discount_pct is not null and ue.discount_pct < 1
       and ue.current_price > 0 then
    round((ue.current_price * (1 - ue.discount_pct)
      - (c.purchase_cost + ue.prep_cost + ue.inbound_cost)
      - ue.storage_fee - ue.fulfillment_fee
      - (ue.referral_fee / ue.current_price)
        * ue.current_price * (1 - ue.discount_pct))
      / (ue.current_price * (1 - ue.discount_pct)), 4)
  end                                                             as discounted_margin_pct,
  -- Target pricing
  ue.desired_profit_pct,
  case when ue.desired_profit_pct is not null
       and (1 - (case when ue.current_price > 0
                      then ue.referral_fee / ue.current_price
                      else 0.15 end) - ue.desired_profit_pct) > 0 then
    round((c.purchase_cost + ue.prep_cost + ue.inbound_cost
           + ue.storage_fee + ue.fulfillment_fee)
      / (1 - (case when ue.current_price > 0
                   then ue.referral_fee / ue.current_price
                   else 0.15 end) - ue.desired_profit_pct), 2)
  end                                                             as suggested_price,
  ue.synced_at,
  ue.updated_at
from public.unit_economics ue
join public.cogs c
  on c.account = ue.account and c.sku = ue.sku;

comment on view public.unit_economics_view is
  'Profit-Calc formulas over cogs + unit_economics: total cost/fee, profit, margin %, BE TACOS, discount planning and desired-profit suggested price.';
