-- Give brands.id an auto-generated default so the console can insert new
-- brands without picking an id itself (avoids duplicate-id races between two
-- people adding at once). Explicitly-provided ids (the seed) still work; the
-- seed ends with setval() so the sequence continues after the highest seeded
-- id.
--
-- Wrapped in a guard so re-running (e.g. via setup.sql) is a no-op.
do $$
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.brands'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    alter table public.brands
      alter column id add generated by default as identity;
  end if;
end
$$;
